text = "  Python Programming  "
print("Original String :", text)
print("Uppercase :", text.upper())
print("Lowercase :", text.lower())
print("Title Case :", text.title())
print("Swap Case :", text.swapcase())
print("Replace Word :", text.replace("Python", "Java"))
print("Remove Spaces :", text.strip())
print("Left Remove Spaces :", text.lstrip())
print("Right Remove Spaces :", text.rstrip())
print("Split String :", text.split())
print("Count Character :", text.count("m"))
print("Find Position :", text.find("Programming"))
print("Starts With Python :", text.startswith("Python"))
print("Ends With Programming :", text.endswith("Programming  "))
print("Check Alphabet :", text.isalpha())
print("Check Number :", text.isdigit())
print("Check AlphaNumeric :", text.isalnum())